# Build and deploy container images to Azure Web App

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureContainerRegistry: wpracr1.azurecr.io
  azureSubscription: wprservicecon

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: DockerInstaller@0
      displayName: Docker Installer
      inputs:
        dockerVersion: 23.0.1
        releaseType: stable

    - task: DockerCompose@0
      displayName: Build services
      inputs:
        action: Build services
        azureSubscriptionEndpoint: $(azureSubscription)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
    
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        action: Push services
        azureSubscriptionEndpoint: $(azureSubscription)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        qualifyImageNames: true
