version: "3.3"

services: 
  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: mongodb
  
  frontend:
    image: wpracr.azurecr.io/frontend:latest
    command: yarn build
    volumes:
      - front:/app/dist
    container_name: frontend

  server:
    image: wpracr.azurecr.io/server:latest
    env_file:
      - .env
    volumes:
      - front:/app/public
    depends_on:
      - mongo
    ports:
      - 80:80
    container_name: server

volumes:
  front:
    driver: azure_file
    driver_opts:
      share_name: wprfile
      storage_account_name: wprshare
